apiVersion: v1
kind: Service
metadata:
  labels:
    app: todo-app
  name: todo-app-svc
  namespace: adoptnext-ns
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: todo-app
  type: NodePort
status:
  loadBalancer: {}
